require("azinch.plugins-setup")

require("azinch.core.options")
require("azinch.core.colorscheme")
require("azinch.core.keymaps")

require("azinch.plugins.comment")
require("azinch.plugins.nvim-tree")
require("azinch.plugins.lualine")
require("azinch.plugins.telescope")
require("azinch.plugins.nvim-cmp")
require("azinch.plugins.lsp.mason")
require("azinch.plugins.lsp.lspsaga")
require("azinch.plugins.lsp.lspconfig")
require("azinch.plugins.lsp.null-ls")
require("azinch.plugins.autopairs")
require("azinch.plugins.treesitter")
require("azinch.plugins.gitsigns")
require("azinch.plugins.flutter-tools")
require("azinch.plugins.flutter-intl")
require("azinch.plugins.color-highlight")
